name: Nasa Mission Control Project
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [14.X, 16.x, 18.x]
        mongodb-version: ['5.3', '6.0']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          node-version: ${{matrix.mongodb-version}}

      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
